### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by elec2** [miroslavpejic85/mirotalkbro#1]
While building I get the following error on Proxmox LXC with alpine:

```
=> ERROR [4/6] RUN npm install                                                                                                        8.1s
------
 > [4/6] RUN npm install:
------
failed to solve: process "/bin/sh -c npm install" did not complete successfully: exit code: 137
```
I changed nothing in .env and docker-compose.yaml.

Is this a problem with LXC?

**Comment by miroslavpejic85** [comment]
Hello @elec2,

To resolve this issue, you can try the following steps:

1. Check your LXC container resources: Ensure that your system has enough memory available to complete the installation process. You can check the memory usage using tools like top or `htop` in a terminal.

2. Update your Node.js and npm versions: Make sure you are using the latest stable versions of [Node.js and npm](https://nodejs.org/en/download). Outdated versions can sometimes cause compatibility issues. You can update Node.js and npm by downloading the latest versions from their respective websites and following the installation instructions.

```bash
# Install NodeJS 18.X and npm
$ sudo apt update
$ sudo apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates
$ curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
$ sudo apt-get install -y nodejs
$ npm install -g npm@latest
```

3. Clear npm cache: Sometimes, issues with the npm cache can cause problems during installation. Clear the npm cache by running the following command:

```shell
npm cache clean --force
```

Retry the installation: Once you have completed the above steps, try running the npm install command again and see if the issue persists. If the problem still persists after following these steps, it may be helpful to provide more details about your Node.js and npm versions, and any relevant configuration or error messages you encounter.

PS: GitHub is mainly for bugs/reqs, please ask questions on the [discord forum](https://discord.gg/rgGYfeYW3N) as specified in the readme.

<img width="831" alt="discord" src="https://github.com/miroslavpejic85/mirotalkbro/assets/70838434/bb29d7c5-1a64-4f00-9005-5dd12207af2a">


Thank you!
