### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by professionalNoob123** [miroslavpejic85/mirotalkbro#3]
I had a feature to request...

Feature Request:
**- Lock Rooms -- (with a password)**

**Comment by miroslavpejic85** [comment]
Hello @professionalNoob123,

I think it's `not necessary` here, as the generated `roomID` is a `UUID4`.

UUID stands for Universally Unique Identifier. It is a 128-bit identifier that is guaranteed to be unique across all devices and all time. UUIDs are commonly used in computer systems and software applications to uniquely identify resources, such as files, databases, network devices, or individual entities.

The "uuid4" refers to a specific version of UUID, known as Version 4. In UUID version 4, the UUIDs are generated using random or pseudo-random numbers. The probability of generating the same UUID is extremely low, making it highly unlikely for collisions to occur.

UUIDs are represented as a sequence of 32 hexadecimal digits, typically grouped into five sections separated by hyphens. For example, a UUIDv4 looks like this: "550e8400-e29b-41d4-a716-446655440000". The specific structure and format of a UUID ensure its uniqueness and make it suitable for various applications, such as distributed systems, database indexing, or generating secure identifiers.

PS: Join with us on [discord forum](https://discord.gg/rgGYfeYW3N), channel: ideas and suggestions, where we can also talking about all together, before to open req here ;)

Thank you!
