### ISSUE TITLE
Video Source - what do you mean ?

### ISSUE THREAD

**Issue by fwn0** [miroslavpejic85/mirotalkbro#4]
Hi Miro,
I can choose only my WebCam for streaming in the WebGui, it not possilble to add and choose any other streaming sources (for example ffmpeg, OBS, streaming servers or streaming engines - maybe over API) ?

**Comment by miroslavpejic85** [comment]
Hi fwn0!,

MiroTalkBRO use the [getUserMedia API](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia), it means you are accessing the user's media devices, such as their webcam and microphone, to capture audio and video input from their device.

In this context, the video source is limited to the media devices available on the user's device, primarily their webcam. You can however rely on OBS and select it as video source which is supported.

![mirotalk-webrtc-bro-obs](https://github.com/miroslavpejic85/mirotalkbro/assets/70838434/0bb86a4a-197c-4127-8787-5c62bcf27e84)

Join us on the [MiroTalk official forum](https://discord.gg/rgGYfeYW3N), where you can find answers to many questions without the need to open an issue here. GitHub ismainly used for reporting confirmed bugs.

Thank you!
Miroslav
