### ISSUE TITLE
NPM install error

### ISSUE THREAD

**Issue by torrswanson** [miroslavpejic85/mirotalkbro#5]
**Error**
Running command `npm install` receives an error and doesn't install node_modules.
```
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN Invalid name: "MiroTalk WebRTC Live Broadcast"
npm WARN mirotalkbro No description
npm WARN mirotalkbro No repository field.
npm WARN mirotalkbro No README data
npm WARN mirotalkbro No license field.

up to date in 1.887s
found 0 vulnerabilities
```

**Fix:**
Rename the field `name` within `package.json` from `MiroTalk WebRTC Live Broadcast` to `mirotalkbroadcast`

**Comment by miroslavpejic85** [comment]
Hey! I was wondering if you'd be open to submitting a Pull Request to change the name to 'mirotlakbro'? Thank you so much!

**Comment by miroslavpejic85** [comment]
Thank you!
