### ISSUE TITLE
Unable to switch cameras on Android device

### ISSUE THREAD

**Issue by marek999** [miroslavpejic85/mirotalkbro#7]
This project is great, but I am having the exact same problem in mirotalkbro as described in [this mirotalk issue](https://github.com/miroslavpejic85/mirotalk/issues/29). The error message I get is exactly the same as [shown for that issue](https://ibb.co/f4GQKQd).
Phone: Moto G7 Power
Android Version: 10
Browser: Chrome

**Comment by miroslavpejic85** [comment]
Thank you for your feedback!

Have you had a chance to check our official **[live demo](https://bro.mirotalk.com)**? It might be related to your device. For further assistance, we invite you to join our **[community forum](https://discord.gg/rgGYfeYW3N)**. There, you can find answers to many common questions and engage with our community, often resolving issues without needing to open it here ;)

**Comment by marek999** [comment]
Yes, I tried the Live Demo, and got the same error message.
I also tried the demo site with a Moto Stylus running Android 12 and Moto G6 running Android 9 with the same result. 
Using Windows 11 Pro when trying to switch from a USB web cam to the built-in laptop camera works as it should.
