### ISSUE TITLE
Public streaming for viewers alongside OpenID integration

### ISSUE THREAD

**Issue by nebulade** [miroslavpejic85/mirotalkbro#8]
### Feature request

Currently if OpenID integration is enabled, both broadcasters and viewers need to authenticate with it. This request is to add the ability to have authentication for broadcasters while also having public streaming for unauthenticated viewers

### Pros

It would open the app for actual broadcasting with the public, while still only allow logged-in users to broadcast.
Already now the viewers can set their usernames independently of OpenID, so it seems it may just be a matter of selectively making auth optional on some routes.

### Additional context

We are about to publish a Cloudron package where have OpenID integration but the main use-case is to have public streams created by authenticated users.

**Comment by miroslavpejic85** [comment]
That makes sense. Please try again. Thank you!

**Comment by nebulade** [comment]
Very nice, it works well. Only a minor thing could be that once the broadcast ends, all viewers get redirected to the login screen, this could be a bit confusing, a placeholder page like "broadcast has ended" or so would be perfect. But that is probably a separate feature request.

**Comment by miroslavpejic85** [comment]
You're welcome, and thank you for the confirmation! I like the idea. Please feel free to open a new feature request and close this one ;)

**Comment by nebulade** [comment]
https://github.com/miroslavpejic85/mirotalkbro/issues/9 so I will close this here.
