### ISSUE TITLE
Add page to redirect users to when a broadcast ended

### ISSUE THREAD

**Issue by nebulade** [miroslavpejic85/mirotalkbro#9]
### Feature request

Currently when a broadcast has ended, all viewers get redirected to the main page (and if OpenID integration is enabled, they get redirected to the login screen).

Would be nice to provide a placeholder page with some basic information that the broadcast has come to an end instead.

### Pros

As a viewer the next step after a broadcast is probably not to login and start a broadcast yourself, so a final page, ideally even with a custom text like "Thanks for joining" would be great.

**Comment by miroslavpejic85** [comment]
I added a custom page that appears when viewers disconnect or leave. 

<img width="791" alt="disconnect" src="https://github.com/user-attachments/assets/0bb029e6-b6fa-4171-94c4-466fb7cd4d01">

**Comment by miroslavpejic85** [comment]
When the broadcaster leaves or a viewer disconnects, the viewer will be redirected to a new page.

![mirotalk-bro-disconnect](https://github.com/user-attachments/assets/a16a1154-b5ae-4c51-9eb2-8a74a802ff98)

Please try it out and let me know if everything is okay. Thank you!
